### ISSUE TITLE
Cache CmdStan install in continuous integration

### ISSUE THREAD

**Issue by wlandau** [stan-dev/cmdstanr#463]
This could shave a couple minutes off the GitHub Actions workflows. Happy to submit a PR.

[This workflow in `stantargets`](https://github.com/wlandau/stantargets/blob/main/.github/workflows/check.yaml)  is a proof of concept.

```yaml
   steps:
      - name: cmdstan env vars
        run: |
          echo "CMDSTAN_PATH=${HOME}/.cmdstanr" >> $GITHUB_ENV
          echo "CMDSTAN_VERSION=2.26.1" >> $GITHUB_ENV
        shell: bash

...

      - name: Cache cmdstan
        uses: actions/cache@v2
        with:
          path: ${{ env.CMDSTAN_PATH }}
          key: ${{ runner.os }}-cmdstan-${{ env.CMDSTAN_VERSION }}
          restore-keys: ${{ runner.os }}-cmdstan-

      - name: Install cmdstan
        run: |
          version <- Sys.getenv("CMDSTAN_VERSION")
          url <- sprintf("https://github.com/stan-dev/cmdstan/releases/download/v%s/cmdstan-%s.tar.gz", version, version)
          cmdstanr::install_cmdstan(cores = 2, release_url = url)
        shell: Rscript {0}
```

Result: 

![Screen Shot 2021-03-10 at 3 11 18 PM](https://user-images.githubusercontent.com/1580860/110691224-e3be6680-81b2-11eb-95a9-903f09cd7eea.png)
